#pragma once

enum ply_save_e
{
  CHARACTER_TIDUS,
  CHARACTER_YUNA,
  CHARACTER_AURON,
  CHARACTER_KIMAHRI,
  CHARACTER_WAKKA,
  CHARACTER_LULU,
  CHARACTER_RIKU,
  CHARACTER_SEYMOUR,
  CHARACTER_VALEFOR,
  CHARACTER_IFRIT,
  CHARACTER_IXION,
  CHARACTER_SHIVA,
  CHARACTER_BAHAMUT,
  CHARACTER_ANIMA,
  CHARACTER_YOJIMBO,
  CHARACTER_CINDY,
  CHARACTER_SANDY,
  CHARACTER_MINDY,
  CHARACTER_DUMMY,
  CHARACTER_DUMMY1
};

enum sphere_grid_type_e
{
  SPHERE_GRID_ORIGINAL,
  SPHERE_GRID_STANDARD,
  SPHERE_GRID_EXPERT
};
